name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  iansinput:
    description: Your input description here
    required: true
    default: '1000'
  MODEL_VERSION:
    description: AI model version
    required: true


# Define your outputs here.
# outputs:
#   time:
#     description: Your output description here

runs:
  using: node22
  main: dist/index.js