name: Test Action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the custom action
        uses: ./
        with:
          MODEL_VERSION: "2000"